spring.application.name=Springboot-SOAP-Demo
server.port = 9090

spring.data.mongodb.host= localhost
spring.data.mongodb.port= 23017
spring.data.mongodb.database= New_DB_Demo
spring.data.mongodb.auto-index-creation= true
